var player = {
    level = 0,
    level_cap = 0,
    speices =  "Mechanical",
    organic = 0,
    mechanic =  0,
    magic = 0,
    Heatlh = 10,
    Mana = 10,
    Strength = 5,
    Defense = 5,
    Dexterity = 5,
    exp = 0,
    exp_cap = 0,
}